# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Default # Asegurarse de usar el nombre del pool que se configuro en azure devops.

jobs:
- job: BuildOnLinux
  displayName: 'Build on Linux'
  pool:
    name: Default
    demands:
      - os -equals linux
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
    displayName: 'Setup Python 3.x on Linux'
    
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m unittest
    displayName: 'Run tests on Linux'

- job: BuildOnWindows
  displayName: 'Build on Windows'
  pool:
    name: Default
    demands:
      - os -equals windows
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'windows'))
    displayName: 'Setup Python 3.x on Windows'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirimientos.txt
    displayName: 'Install dependencies'

  - script: |
      python -m unittest
    displayName: 'Run tests on Windows'

