# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Default # Asegurarse de usar el nombre del pool que se configuro en azure devops.

jobs:
- job: BuildOnLinux
  displayName: 'Build on Linux'
  pool:
    name: Default
    demands:
      - os -equals linux
  steps:    
  - script: |
      python3 -m venv venv1
      source venv1/bin/activate
      echo "configurando python3"
      set PATH=\usr\bin\Python3;%PATH%
      python3 --version 
      python3 -m pip install --upgrade pip
      pip install -r requerimientos.txt
      
    displayName: 'Instalacion dependencias y run tests'  

- job: BuildOnWindows
  displayName: 'Build on Windows'
  pool:
    name: Default
    demands:
      - os -equals windows
  steps:
  - script: |
      echo "configurando python 3.12"
      set PATH=C:\agent\_work\_tool\Python\3.12.0\x64\Python312;%PATH%
      python --version 
      python -m pip install --upgrade pip
      pip install -r requerimientos.txt
      
    displayName: 'Instalacion dependencias y run tests'
  

