#aun pendiente de cambio de variables


trigger:
- test  # Se ejecuta al hacer push en main

pool:
  name: Default  # Asegúrate de que sea el nombre del pool correcto

variables:
  azureSubscription: 'NombreDeTuConexionAzure'  # Nombre de la conexión de servicio en Azure DevOps
  acrName: 'TuACR.azurecr.io'  # Nombre de tu Azure Container Registry
  imageName: 'mi-api'  # Nombre de la imagen Docker
  appServiceName: 'mi-app-service'  # Nombre de tu App Service en Azure

stages:
- stage: Build
  displayName: 'Construir y publicar imagen Docker'
  jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Construcción y publicación de imagen Docker'
    steps:
      - task: Docker@2
        displayName: 'Autenticación en ACR'
        inputs:
          command: 'login'
          containerRegistry: '$(azureSubscription)'

      - task: Docker@2
        displayName: 'Construir la imagen Docker'
        inputs:
          command: 'build'
          dockerfile: 'Dockerfile'
          repository: '$(acrName)/$(imageName)'
          tags: 'latest'

      - task: Docker@2
        displayName: 'Subir imagen a ACR'
        inputs:
          command: 'push'
          repository: '$(acrName)/$(imageName)'
          tags: 'latest'

- stage: Deploy
  displayName: 'Desplegar en Azure App Service'
  dependsOn: Build
  jobs:
  - job: DeployToAzure
    displayName: 'Desplegar en Azure'
    steps:
      - task: AzureWebAppContainer@1
        displayName: 'Desplegar contenedor en App Service'
        inputs:
          azureSubscription: '$(azureSubscription)'
          appName: '$(appServiceName)'
          containers: '$(acrName)/$(imageName):latest'