# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test  # Se ejecuta al hacer push a la rama main

pool:
  name: Default  # Se ejecuta en una máquina virtual Ubuntu

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'  # Especifica la versión de Python

- script: |
    echo "configurando python 3.12"
    set PATH=C:\agent\_work\_tool\Python\3.12.0\x64\Python312;%PATH%
    python --version
    python -m venv venv2
    call venv2\Scripts\activate.bat
    python -m pip install --upgrade pip
    pip install -r requerimientos.txt # Instala las dependencias
  displayName: 'configuracion de ambiente e instalacion de dependencias'

- script: |
    call venv2\Scripts\activate.bat
    pytest  # Ejecuta las pruebas
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop1'
    publishLocation: 'Container'


